pracstudy = [
    {"stimulus":"<p style='font-size: 48px;'>BRICK - <span style='color: green'>TRICK</span></p>","data":{"type":"old","category":"produce","word":"TRICK"}},
    {"stimulus":"<p style='font-size: 48px;'>FAT - <span style='color: green'>BAT</span></p>","data":{"type":"old","category":"produce","word":"BAT"}},
    {"stimulus":"<p style='font-size: 48px;'>CAT - <span style='color: green'>HAT</span></p>","data":{"type":"old","category":"produce","word":"HAT"}},
    {"stimulus":"<p style='font-size: 48px;'>POWER - <span style='color: green'>TOWER</span></p>","data":{"type":"old","category":"produce","word":"TOWER"}},
    {"stimulus":"<p style='font-size: 48px;'>MAT - <span style='color: green'>RAT</span></p>","data":{"type":"old","category":"produce","word":"RAT"}},
    {"stimulus":"<p style='font-size: 48px;'>TIN - <span style='color: green'>PIN</span></p>","data":{"type":"old","category":"produce","word":"PIN"}},
    {"stimulus":"<p style='font-size: 48px;'>PEA - <span style='color: green'>TEA</span></p>","data":{"type":"old","category":"produce","word":"TEA"}},
    {"stimulus":"<p style='font-size: 48px;'>TEN - <span style='color: green'>PEN</span></p>","data":{"type":"old","category":"produce","word":"PEN"}},
    {"stimulus":"<p style='font-size: 48px;'>BAD - <span style='color: red'>MAD</span></p>","data":{"type":"old","category":"read","word":"MAD"}},
    {"stimulus":"<p style='font-size: 48px;'>LOG - <span style='color: red'>DOG</span></p>","data":{"type":"old","category":"read","word":"DOG"}},
    {"stimulus":"<p style='font-size: 48px;'>FAN - <span style='color: red'>MAN</span></p>","data":{"type":"old","category":"read","word":"MAN"}},
    {"stimulus":"<p style='font-size: 48px;'>SHEER - <span style='color: red'>CHEER</span></p>","data":{"type":"old","category":"read","word":"CHEER"}},
    {"stimulus":"<p style='font-size: 48px;'>GRAVE - <span style='color: red'>BRAVE</span></p>","data":{"type":"old","category":"read","word":"BRAVE"}},
    {"stimulus":"<p style='font-size: 48px;'>MONEY - <span style='color: red'>HONEY</span></p>","data":{"type":"old","category":"read","word":"HONEY"}},
    {"stimulus":"<p style='font-size: 48px;'>BOW - <span style='color: red'>WOW</span></p>","data":{"type":"old","category":"read","word":"WOW"}},
    {"stimulus":"<p style='font-size: 48px;'>ROT - <span style='color: red'>LOT</span></p>","data":{"type":"old","category":"read","word":"LOT"}},
]